### ISSUE TITLE
Support "Embedded Objects"

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#18] opened 2020-02-17 17:01 UTC
Dear @doug-martin ,

first of all, I would like to say, that this library is really (!) awesome :+1: great work so far!

I recently stumbled upon an issue I am not quite sure how to solve it. Let me describe it in more detail.
Consider the following (simplified) example: I have a `UserEntity` and corresponding `UserObjectType`.
Furthermore, this `User` has a `settings` property, which is stored as JSON in the database. However, the object itself may have a proper class in order to indicate valid setting parameters, like `language`, `color` or whatever.

My `update-user.input.ts` looks like this (only important parts):
```ts
@InputType()
export class UpdateUserInput {
  @IsOptional()
  @IsString()
  @Field({
    description: 'The new username',
    nullable: true
  })
  username: string;

  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateSettingsInput)
  @Field(type => UpdateSettingsInput, {
    description: 'Settings Object for this user',
    nullable: true
  })
  settingst: object;
}
```

whereas my `UpdateSettingsInput` class looks like this
```ts
import { CoreInput } from '@cancerlog/api/core';
import { InputType, Field } from 'type-graphql';
import { IsOptional, IsString } from 'class-validator';

@InputType()
export class UpdateSettingsInput {
  @IsOptional()
  @IsString()
  @Field({
    nullable: true
  })
  language: string;

  @IsOptional()
  @IsString()
  @Field({
    nullable: true
  })
  theme: string;

  // ... more fields here
}
```

Updating a `User` and setting the data for `settings` works like a charm, however, I am not able to `read` the data and return it to the client properly.

My `UserObject` looks like this:
```ts
@ObjectType('User')
export class UserObject {
  // ... some fields here
  @Field(() => SettingsObject, {
    nullable: true
  })
  settings: SettingsObject;
}
```
with a corresponding `SettingsObject` (looks similar to the `UpdateSettingsInput` class).

When "compiling" the app, it throws an error with:
```
(node:28196) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL input type for settings
```

I assume, that this is some weird "black magic" stuff happening in this library for auto-generating the CRUD methods and its not properly able to do so.

Please note, that i also tried to use the `relations` approach on the `UserResolver` class to add a `one` relationship to `settings`. This is, however, not possible, because this is (obviously) not a valid `TypeORM` relationship, but rather an "embedded" object.

Can you please point me into the right direction?! :cry: Am i missing something, does this library not have proper support for such a feature or am i just dumb? :laughing: 

Thank you so much for your time and advices,
Johannes

**Comment by doug-martin** [comment] 2020-02-17 17:14
Can show me what your resolver looks like?

**Comment by johannesschobel** [comment] 2020-02-17 17:20
Dear @doug-martin , I will post my resolver tomorrow. I have already left office, sorry

**Comment by johannesschobel** [comment] 2020-02-18 06:57
My `UserResolver` looks like this:

```ts
@Resolver()
export class UserResolver extends CRUDResolver(UserObject, {
  create: { many: { disabled: true }, CreateDTOClass: CreateUserInput },
  delete: { disabled: true },
  update: { many: { disabled: true }, UpdateDTOClass: UpdateUserInput },
  relations: {
    one: {
      // ... here are some relationships
      },
    many: {
      // ... here are some relationships
      }
    }
  }
}) {
  constructor(readonly service: UserService {
    super(service);
  }
}
```

It may be possible to directly apply some kind of `@ResolveProperty()` decorators from `type-graphql`, but i have not tried it yet. What is the common "go-to" strat here with your library?

Thank you very much for this awesome support!

**Comment by johannesschobel** [comment] 2020-02-18 07:08
ok.. adding a custom `resolve`-method for this particular field works.. I did it like this:
```ts
@Resolver(of => ScreeningObject)
export class UserResolver extends CRUDResolver(UserObject, {
// definition is the same
}) {
  // ... constructor
  @ResolveProperty('settings', returns => SettingsObject, {
    description: 'User Settings',
    nullable: true
  })
  resolveSettings(@Parent() parent: UserEntity) {
    return parent.settings;
  }
}
```

But is this the "best" approach?

**Comment by doug-martin** [comment] 2020-02-18 16:28
@johannesschobel could you provided a small example repo? There are a couple of things it could be.

**Comment by johannesschobel** [comment] 2020-02-18 16:29
i will try to work on an example repo during the weekend..

**Comment by doug-martin** [comment] 2020-02-22 19:39
@johannesschobel I've played with this and I cant seem to reproduce. I pushed up an example to https://github.com/doug-martin/nestjs-query/tree/issue18 its slightly more complex as I was trying different ways to break it, in this example I added a checklist array to my TodoItem.

Here is where all the changes took place https://github.com/doug-martin/nestjs-query/tree/issue18/examples/nest-graphql-typeorm/src/todo-item

Diff view: https://github.com/doug-martin/nestjs-query/compare/issue18?expand=1

**Comment by johannesschobel** [comment] 2020-02-24 07:01
i will try to give feedback during the week.. first, i need to adapt to your latest changes :) thank you very much for being so active on this repo!

**Comment by doug-martin** [comment] 2020-03-02 03:38
@johannesschobel is this still an issue?

**Comment by johannesschobel** [comment] 2020-03-02 10:37
Dear @doug-martin , actually yes, but i wasn't able to prepare a repo for you as i was very busy last week :( (there are currently exams at university)

**Comment by doug-martin** [comment] 2020-04-26 05:08
Closing for now, if you come provide a repo with an example you can comment on here or open a new issue.

**Closed by doug-martin** 2020-04-26 05:08 UTC
