### ISSUE TITLE
Can not fetch totalCount.

### ISSUE THREAD

**Issue by smtaha512** [doug-martin/nestjs-query#753] opened 2020-12-08 12:33 UTC
I am using Graphql and TypeORM and trying to fetch totalCount using cursor-based pagination. But it throws the following error:
![image](https://user-images.githubusercontent.com/10245369/101484093-e96d9b80-397a-11eb-91bf-785dccab307c.png)
My module, resolver, and service are as follows:

**Module:**
 ```ts
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { Module } from '@nestjs/common';
import { HandbookEntity } from './entities/handbook.entity';
import { HandbookResolver } from './handbook.resolver';
import { HandbookService } from './handbook.service';
import { HandbookRepository } from './repositories/handbook.repository';

@Module({
  imports: [NestjsQueryTypeOrmModule.forFeature([HandbookEntity, HandbookRepository])],
  providers: [HandbookResolver, HandbookService],
})
export class HandbookModule {}
```
**Resolver:**
```ts
import { CRUDResolver } from '@nestjs-query/query-graphql';
import { Resolver } from '@nestjs/graphql';
import { CreateHandbookInput } from './dto/create-handbook.input';
import { HandbookDto } from './dto/handbook.dto';
import { UpdateHandbookInput } from './dto/update-handbook.input';
import { HandbookService } from './handbook.service';

@Resolver(() => HandbookDto)
export class HandbookResolver extends CRUDResolver(HandbookDto, {
  CreateDTOClass: CreateHandbookInput,
  UpdateDTOClass: UpdateHandbookInput,
  enableTotalCount: true,
}) {
  constructor(handbookService: HandbookService) {
    super(handbookService);
  }
}
```
**Service:**
```ts
import { QueryService } from '@nestjs-query/core';
import { TypeOrmQueryService } from '@nestjs-query/query-typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { HandbookEntity } from './entities/handbook.entity';
import { HandbookRepository } from './repositories/handbook.repository';

@QueryService(HandbookEntity)
export class HandbookService extends TypeOrmQueryService<HandbookEntity> {
  constructor(
    @InjectRepository(HandbookRepository) private readonly repository: HandbookRepository,
  ) {
    super(repository, { useSoftDelete: true });
  }
}

```
Could you please help me figure out what I am missing?

**Comment by petyunchik** [comment] 2020-12-08 20:52
I can confirm the problem - It seems there is some bug when you extend `CRUDResolver` class (and perhaps other resolver classes too). 

Same problem when querying relations on extended `CRUDResolver`: `Cannot return null for non-nullable field ...`

I've tried to declare identical options from of `NestjsQueryGraphQLModule.forFeature` `resolvers` and querying works without any problems. So the problem only appears when resolver created manually.

**Comment by doug-martin** [comment] 2020-12-10 23:40
@smtaha512 @petyunchik thank you for the bug report!

I tried to replicate locally and it worked as expected you can see my example [here](https://github.com/doug-martin/nestjs-query/tree/issue753/examples/basic/src/todo-item). 

@smtaha512 what is `HandBookRepository`? Does it conform to the same interface as a normal TypeOrm repository?

Couple of questions to maybe help narrow it down
* Does the table have data?
* Does your Resolver decorator have have the type `e.g. @Resolver(() => TodoItemDTO)`
* What version of nests-query are you using for each package?

**Comment by smtaha512** [comment] 2020-12-11 11:02
@doug-martin, yes `HandbookRepository` is actually a class that extends `Repository` from TypeOrm. Please check the attached code snippets:

**Handbook Repository**

```ts
import { EntityRepository } from 'typeorm';
import { BaseRepository } from '../../../shared/repositories/base.repository';
import { HandbookEntity } from '../entities/handbook.entity';

@EntityRepository(HandbookEntity)
export class HandbookRepository extends BaseRepository<HandbookEntity> {}
```

**BaseRepository**

```ts
import { FindConditions, FindManyOptions, ObjectLiteral, Repository } from 'typeorm';

export abstract class BaseRepository<T extends ObjectLiteral> extends Repository<T> {
  findById(id: string, options?: FindManyOptions<T>): Promise<T> {
    return super.findByIds([id], options).then(([entity]) => entity);
  }
}
```

> Couple of questions to maybe help narrow it down
>
> - Does the table have data?
> - Does your Resolver decorator have have the type e.g. @Resolver(() => TodoItemDTO)
> - What version of nests-query are you using for each package?

**Answers:**
- Yes the table has data. I am actually adding 10 rows as seed.
- Yes, My Resolver decorator has the type. It is `@Resolver(() => HandbookDto)`
- The versions I am using are:

```json
"dependencies": {
    "@nestjs-query/core": "^0.21.2",
    "@nestjs-query/query-graphql": "^0.21.2",
    "@nestjs-query/query-typeorm": "^0.21.2",
}
```

**Comment by doug-martin** [comment] 2020-12-11 23:06
@smtaha512 I tried to create a custom repository using the code you provided, but when the repository is injected the `manager` property is null so none of the default methods work. Would you mind trying not using a custom repo and see if it works? 

```ts
import { QueryService } from '@nestjs-query/core';
import { TypeOrmQueryService } from '@nestjs-query/query-typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { HandbookEntity } from './entities/handbook.entity';
import { HandbookRepository } from './repositories/handbook.repository';

@QueryService(HandbookEntity)
export class HandbookService extends TypeOrmQueryService<HandbookEntity> {
  constructor(
    @InjectRepository(HandbookEntity) private readonly repository: Repository<HandbookEntity>,
  ) {
    super(repository, { useSoftDelete: true });
  }
}
```

**Comment by doug-martin** [comment] 2020-12-11 23:12
@smtaha512 would you mind also sharing your DTO and Entity definition incase its something in there?

**Comment by petyunchik** [comment] 2020-12-13 15:50
@doug-martin thanks for pointing out - in my case Resolver decorator didn't have a type/DTO and that's why there was an issue.

**Comment by smtaha512** [comment] 2020-12-16 10:23
> @smtaha512 I tried to create a custom repository using the code you provided, but when the repository is injected the `manager` property is null so none of the default methods work. Would you mind trying not using a custom repo and see if it works?
> 
> ```ts
> import { QueryService } from '@nestjs-query/core';
> import { TypeOrmQueryService } from '@nestjs-query/query-typeorm';
> import { InjectRepository } from '@nestjs/typeorm';
> import { Repository } from 'typeorm';
> import { HandbookEntity } from './entities/handbook.entity';
> import { HandbookRepository } from './repositories/handbook.repository';
> 
> @QueryService(HandbookEntity)
> export class HandbookService extends TypeOrmQueryService<HandbookEntity> {
>   constructor(
>     @InjectRepository(HandbookEntity) private readonly repository: Repository<HandbookEntity>,
>   ) {
>     super(repository, { useSoftDelete: true });
>   }
> }
> ```

@doug-martin I tried injecting the repository directly using the following method:
```ts
    @InjectRepository(HandbookEntity) repository: Repository<HandbookEntity>,
```
It is also throwing the same error for me. Is it working for you?

**Comment by smtaha512** [comment] 2020-12-16 10:28
> @smtaha512 would you mind also sharing your DTO and Entity definition incase its something in there?

Here is the entity:
```ts
@Entity({ name: 'handbooks' })
export class HandbookEntity extends BaseEntity<HandbookEntity> {
  @Column('varchar')
  name: string;

  @OneToMany(
    () => WidgetEntity,
    widget => widget.handbook,
  )
  widgets: WidgetEntity[];

  @OneToMany(
    () => TeamHandbookEntity,
    teamHandbooks => teamHandbooks.handbook,
  )
  handbookTeams: TeamHandbookEntity[];

  constructor(entity: Partial<HandbookEntity>) {
    super(entity);
    Object.assign(this, entity);
  }
}
```
**Base Entity:**

```ts
@ObjectType()
export abstract class BaseEntity<T> {
  @PrimaryGeneratedColumn('uuid') id: string;

  @UpdateDateColumn({ name: 'updated_at' }) updatedAt: string;

  @CreateDateColumn({ name: 'created_at' }) createdAt: string;

  @DeleteDateColumn({ name: 'deleted_at' }) deletedAt: string;

  constructor(entity: Partial<BaseEntity<T>>) {
    const { createdAt, deletedAt, id, updatedAt } = entity ?? {};
    Object.assign(this, { createdAt, deletedAt, id, updatedAt });
  }
}
```

**DTO**

```ts
@ObjectType('Handbook')
@Relation('widget', () => [WidgetDto], { enableAggregate: true, dtoName: 'widget' })
@FilterableRelation('team', () => [TeamDto], {
  enableAggregate: !true,
  dtoName: 'team',
  relationName: 'teamHandbooks',
  disableUpdate: true,
  disableRemove: true,
})
export class HandbookDto extends GqlBaseResponseDto<HandbookDto> {
  @FilterableField(() => String)
  name!: string;
}
```

**Comment by doug-martin** [comment] 2020-12-16 20:32
> > @smtaha512 I tried to create a custom repository using the code you provided, but when the repository is injected the `manager` property is null so none of the default methods work. Would you mind trying not using a custom repo and see if it works?
> > ```ts
> > import { QueryService } from '@nestjs-query/core';
> > import { TypeOrmQueryService } from '@nestjs-query/query-typeorm';
> > import { InjectRepository } from '@nestjs/typeorm';
> > import { Repository } from 'typeorm';
> > import { HandbookEntity } from './entities/handbook.entity';
> > import { HandbookRepository } from './repositories/handbook.repository';
> > 
> > @QueryService(HandbookEntity)
> > export class HandbookService extends TypeOrmQueryService<HandbookEntity> {
> >   constructor(
> >     @InjectRepository(HandbookEntity) private readonly repository: Repository<HandbookEntity>,
> >   ) {
> >     super(repository, { useSoftDelete: true });
> >   }
> > }
> > ```
> 
> @doug-martin I tried injecting the repository directly using the following method:
> 
> ```ts
>     @InjectRepository(HandbookEntity) repository: Repository<HandbookEntity>,
> ```
> 
> It is also throwing the same error for me. Is it working for you?

When you did this did you remove your custom repository from the module, if you don't it will still inject the custom one and not work.

```ts
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { Module } from '@nestjs/common';
import { HandbookEntity } from './entities/handbook.entity';
import { HandbookResolver } from './handbook.resolver';
import { HandbookService } from './handbook.service';
import { HandbookRepository } from './repositories/handbook.repository';

@Module({
 imports: [NestjsQueryTypeOrmModule.forFeature([HandbookEntity])],
 providers: [HandbookResolver, HandbookService],
})
export class HandbookModule {}
```

**Comment by smtaha512** [comment] 2020-12-22 15:53
> @smtaha512 would you mind also sharing your DTO and Entity definition incase its something in there?

Sorry for the late reply, I was suffering from dengue fever.

Here are my DTOs and Entity definitions.

**Handbook DTO**
```ts
@ObjectType('Handbook')
@Relation('widget', () => [WidgetDto], { enableAggregate: true, dtoName: 'widget' })
@FilterableRelation('team', () => [TeamDto], {
  enableAggregate: !true,
  dtoName: 'team',
  relationName: 'teamHandbooks',
  disableUpdate: true,
  disableRemove: true,
})
export class HandbookDto extends GqlBaseResponseDto<HandbookDto> {
  @FilterableField(() => String)
  name!: string;
}
```

**GqlBaseResponseDto**
```ts
@ObjectType({ isAbstract: true })
export abstract class GqlBaseResponseDto<T> {
  @FilterableField(() => ID)
  id!: string;

  @FilterableField(() => String)
  createdAt!: string;

  @FilterableField(() => String)
  updatedAt!: string;

  constructor(dto: Partial<GqlBaseResponseDto<T>>) {
    Object.assign(this, dto);
  }
}
```

**Handbook Entity**
```ts
@Entity({ name: 'handbooks' })
export class HandbookEntity extends BaseEntity<HandbookEntity> {
  @Column('varchar')
  name: string;

  @OneToMany(
    () => WidgetEntity,
    widget => widget.handbook,
  )
  widgets: WidgetEntity[];

  @OneToMany(
    () => TeamHandbookEntity,
    teamHandbooks => teamHandbooks.handbook,
  )
  handbookTeams: TeamHandbookEntity[];

  constructor(entity: Partial<HandbookEntity>) {
    super(entity);
    Object.assign(this, entity);
  }
}
```

**Base Entity**
```ts
@ObjectType()
export abstract class BaseEntity<T> {
  @PrimaryGeneratedColumn('uuid') id: string;

  @UpdateDateColumn({ name: 'updated_at' }) updatedAt: string;

  @CreateDateColumn({ name: 'created_at' }) createdAt: string;

  @DeleteDateColumn({ name: 'deleted_at' }) deletedAt: string;

  constructor(entity: Partial<BaseEntity<T>>) {
    const { createdAt, deletedAt, id, updatedAt } = entity ?? {};
    Object.assign(this, { createdAt, deletedAt, id, updatedAt });
  }
}
```

**Comment by smtaha512** [comment] 2020-12-22 15:54
> When you did this did you remove your custom repository from the module, if you don't it will still inject the custom one and not work.

Yes. I removed the custom repository from the module but getting the same error.

**Comment by doug-martin** [comment] 2021-02-26 06:13
@smtaha512 I'm not sure if you found a work around, but if you can provide a repo that demonstrates the issue, I'll look into it more. Without that I'm afraid I won't be able to help you.

**Comment by doug-martin** [comment] 2021-03-22 03:37
Closing for now. If I can get a repo that reproduces the issue I'll reopen and look into it more.

**Closed** 2021-03-22 03:37 UTC
Labels: GraphQL, bug, investigate

**Comment by bruce-shi** [comment] 2021-04-07 07:46
`totalCount` is actually a getter method. Check if you have enabled `ClassSerializerInterceptor`. I fixed this error by removing it.  Because `ClassSerializerInterceptor` is using `class-transformer` and you need an `@Expose` decorator to expose the getter method. 

[https://github.com/typestack/class-transformer#exposing-getters-and-method-return-values](url)

**Comment by giladaya** [comment] 2021-07-12 09:12
@bruce-shi I have the same issue and have `ClassSerializerInterceptor` enabled.
To clarify - did you remove `ClassSerializerInterceptor`? What did you use instead?
Is there another possible solution?

**Comment by truonghdpk** [comment] 2022-05-25 08:37
@bruce-shi  thanks i removed ClassSerializerInterceptor and it's work

**Comment by Leonatglobal** [comment] 2022-07-20 06:45
> `totalCount` is actually a getter method. Check if you have enabled `ClassSerializerInterceptor`. I fixed this error by removing it. Because `ClassSerializerInterceptor` is using `class-transformer` and you need an `@Expose` decorator to expose the getter method.
> 
> [https://github.com/typestack/class-transformer#exposing-getters-and-method-return-values](url)

If remove ClassSerializerInterceptor there will raise another error: 'ReferenceError: validator is not defined' at AbstractConnection.get totalCount (... offset-connection.type.ts).
It's a bug of getter method of totalCount on co-working with ClassSerializerInterceptor.
